--USUARIO
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER LOTTUS_DREAM_ADMIN IDENTIFIED BY Q1w2e3r4t5y6
TEMPORARY TABLESPACE "TEMP";

ALTER USER LOTTUS_DREAM_ADMIN QUOTA UNLIMITED ON USERS;
GRANT "RESOURCE" TO LOTTUS_DREAM_ADMIN;
GRANT "CONNECT" TO LOTTUS_DREAM_ADMIN;
ALTER USER LOTTUS_DREAM_ADMIN DEFAULT ROLE "RESOURCE","CONNECT";

--TABLAS
CREATE TABLE USUARIO(
    RUT         VARCHAR2(12) PRIMARY KEY NOT NULL,
    NOMBRE      VARCHAR2(60) NOT NULL,
    APELLIDO    VARCHAR2(60) NOT NULL,
    CORREO      VARCHAR2(60) NOT NULL,
    CLAVE  		VARCHAR2(60) NOT NULL,
    FECHA_NAC   VARCHAR2(12),
    FONO        NUMBER(9),
    CARGO       VARCHAR2(60) NOT NULL,
    OFICINA     VARCHAR2(60) NOT NULL,
    TIPO        VARCHAR2(60) NOT NULL
);

CREATE TABLE PROVEEDOR(
    ID			         NUMBER(9) PRIMARY KEY NOT NULL,
    NOMBRE               VARCHAR2(60) NOT NULL,
    REPRESENTANTE		 VARCHAR2(60) NOT NULL,
    DIRECCION            VARCHAR2(60) NOT NULL,
    TIPO                 VARCHAR2(60) NOT NULL,
    DETALLE              VARCHAR2(60) NOT NULL
);

CREATE TABLE SALON(
    ID		           	NUMBER(9) PRIMARY KEY NOT NULL,
    NOMBRE       		VARCHAR2(60) NOT NULL,
    ESTADO             	VARCHAR2(60) NOT NULL,
    UBICACION          	VARCHAR2(60) NOT NULL,
    COMUNA              VARCHAR2(60) NOT NULL
);

CREATE TABLE EVENTO(
    ID        				 NUMBER(9) PRIMARY KEY NOT NULL,
    NOMBRE                   VARCHAR2(60) NOT NULL,
    CANT_PERSONAS            VARCHAR2(60) NOT NULL
);

CREATE TABLE COTIZACION(
    ID                  NUMBER(9) PRIMARY KEY NOT NULL,
    NOMBRE              VARCHAR2(60) NOT NULL,
    APELLIDO            VARCHAR2(60) NOT NULL,
    RUT                 VARCHAR2(12),
    CORREO              VARCHAR2(60) NOT NULL,
    TELEFONO            NUMBER(9),
    CANT_PERSONAS       NUMBER(5) NOT NULL,
    HORA_INICIO         VARCHAR2(20) NOT NULL,
    HORA_FIN            VARCHAR2(20) NOT NULL,
    FECHA               VARCHAR2(12) NOT NULL,
    ID_EVENTO           NUMBER(9) NOT NULL,
    DETALLE             VARCHAR2(150) NOT NULL,
    ID_SALON            NUMBER(9) NOT NULL,
    CONSTRAINT COTIZACION_EVENTO_FK FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO (ID),
	CONSTRAINT COTIZACION_SALON_FK FOREIGN KEY (ID_SALON) REFERENCES SALON (ID),
    CONSTRAINT COTIZACION_USUARIO_FK FOREIGN KEY (RUT) REFERENCES USUARIO (RUT)
);

CREATE TABLE SERVICIO(
    ID			         NUMBER(9) PRIMARY KEY NOT NULL,
    NOMBRE               VARCHAR2(60) NOT NULL,
    DESCRIPCION          VARCHAR2(60) NOT NULL,
    ID_PROVEEDOR         NUMBER(9) NOT NULL,
    CONSTRAINT EVENTO_PROVEEDOR_FK FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID)
);

--DATOS
INSERT INTO USUARIO VALUES ('18222333-0','JUAN','FLORES','jflores@gmail.com','q1w2e3r4t5y6','21-05-1978',966551872,'N/A','N/A','USUARIO');
INSERT INTO USUARIO VALUES ('16358050-7','MELISSA','URZUA','meliurzua@gmail.com','q1w2e3r4t5y6','27-05-1988',94466778,'N/A','N/A','USUARIO');
INSERT INTO USUARIO VALUES ('12532663-4','EMILIA','SOTO','esotosuz@gmail.com','q1w2e3r4t5y6','02-08-1968',96587432,'ADMINISTRADORA/REPRESENTANTE','AV. RAUL LABBE 14190, LO BARNECHEA','ADMINISTRADOR');


INSERT INTO EVENTO VALUES (001,'CUMPLEAÑOS','60');
INSERT INTO EVENTO VALUES (002,'BODAS','200');
INSERT INTO EVENTO VALUES (003,'EVENTOS SOCIALES','200');
INSERT INTO EVENTO VALUES (004,'EVENTOS EMPRESARIALES','150');


INSERT INTO PROVEEDOR VALUES (001,'DJ ASTOKIID','LEANDRO TORRES','AV. PROVIDENCIA 1043, DEPTO 521, PROVIDENCIA','MUSICA EN LOS EVENTOS','N/A');
INSERT INTO PROVEEDOR VALUES (002,'LA CORTE ELITE','ANDREA VARGAS','DR. CARLOS LORCA TOBAR 644, RECOLETA','SERVICIO DE MESEROS','N/A');
INSERT INTO PROVEEDOR VALUES (003,'BANQUETERIA Y EVENTOS','ELOISA MARTINEZ','GABRIEL PALMA 640, RECOLETA','SERVICIO DE BANQUETERIA','N/A');
INSERT INTO PROVEEDOR VALUES (004,'DECORACIONES DE EVENTOS Y CELEBRACIONES EIRL','VICTOR PALMA','ARGOMEDO 140, 8330398, SANTIAGO','SERVICIO DE DECORACIONES','N/A');
INSERT INTO PROVEEDOR VALUES (005,'JUAN PELLICER','JUAN PELLICER','HUERFANOS 714, SANTIAGO','SERVICIO DE FOTOGRAFO','N/A');
INSERT INTO PROVEEDOR VALUES (006,'GASFITERIA ZABALA','MATIAS ZABALA','SANTO DOMINGO 1240, SANTIAGO','GASFITER','N/A');
INSERT INTO PROVEEDOR VALUES (007,'ELECTRICO AUTORIZADO SEC','SEC','LORD COCHRANE 664, SANTIAGO','ELECTRICISTA','N/A');
INSERT INTO PROVEEDOR VALUES (008,'GARCIA QUILCHE CONSTRUCCIONES Y REMODELACIONES','ROBERTO GARCIA','SAN FERNANDO 1477, CONCHALI','CONSTRUCCION Y REMODELACIONES','N/A');
INSERT INTO PROVEEDOR VALUES (009,'INGETECH S.A.','LILANA MUNOZ','MALAQUIAS CONCHA 60, PROVIDENCIA','SERVICIO DE GUARDIAS','N/A');
INSERT INTO PROVEEDOR VALUES (010,'SERVICIO DE LIMPIEZA LTDA','ANDREA TAPIA','ANGAMOS 298, SANTIAGO','SERVICIO DE LIMPIEZA','N/A');

INSERT INTO SALON VALUES (001,'SALON ANDROMEDA','DISPONIBLE','AV. RAUL LABBE 14190', 'LO BARNECHEA');
INSERT INTO SALON VALUES (002,'SALON CASIOPEA','RESERVADO','AV. VICUÑA MACKENNA 3314', 'LA FLORIDA');
INSERT INTO SALON VALUES (003,'SALON ORION','DISPONIBLE','LAS HUALTATAS 5754', 'VITACURA');
INSERT INTO SALON VALUES (004,'SALON DORADO','DISPONIBLE','AV. RAUL LABBE 14190', 'LO BARNECHEA');
INSERT INTO SALON VALUES (005,'SALON DEL LOTO','RESERVADO','AV. RAUL LABBE 14190', 'LO BARNECHEA');

INSERT INTO COTIZACION VALUES (001,'MELISSA','URZUA','16358050-7','meliurzua@gmail.com',94466778,30,'18:00','00:00','27-05-2023',001,'TEMÁTICA SUPER HEROES',002);

INSERT INTO SERVICIO VALUES (001,'DECORACIONES DE EVENTOS Y CELEBRACIONES EIRL','SERVICIO DECORACIONES',004);

--CONSULTAS
SELECT * FROM USUARIO;
SELECT * FROM EVENTO;
SELECT * FROM PROVEEDOR;
SELECT * FROM SALON;
SELECT * FROM SERVICIO;
SELECT * FROM COTIZACION;
