# Generated by Django 4.2 on 2023-04-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_administrador2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador2',
        ),
    ]
