# Generated by Django 4.2 on 2023-04-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cliente_cotizacion_evento_proveedor_salon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='apellido')),
                ('correo', models.CharField(max_length=60, verbose_name='correo')),
                ('fecha_nac', models.DateField(verbose_name='fecha de nacimiento')),
                ('fono', models.IntegerField(verbose_name='fono')),
                ('cargo', models.CharField(max_length=60, verbose_name='cargo del administrador')),
                ('oficina', models.CharField(max_length=60, verbose_name='oficina del administrador')),
                ('tipo', models.CharField(max_length=60, verbose_name='tipo de usuario')),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
