# Generated by Django 4.2 on 2023-04-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
