# Generated by Django 4.2 on 2023-04-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
