# Generated by Django 4.2 on 2023-04-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={},
        ),
    ]
