# Generated by Django 4.2 on 2023-04-29 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cotizacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'managed': False},
        ),
    ]
