# Generated by Django 4.2 on 2023-04-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cotizacion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=60, verbose_name='descripcion')),
                ('id_evento', models.IntegerField(verbose_name='id evento')),
                ('id_salon', models.IntegerField(verbose_name='id salon')),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Servicio_evento',
        ),
    ]
